# Updated content
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: url_shortener_api_development
  # Remove username and password, ensure development database is accessible
  # based on your local setup, possibly using environment variables if needed.

test:
  <<: *default
  database: url_shortener_api_test
  # Ensure the test database configuration is suitable for your CI/CD setup or
  # local testing environment.

production:
  <<: *default
  # For production, we leverage the DATABASE_URL environment variable
  # provided by Render or your production environment.
  # This single line replaces the hardcoded database, username, and password.
